# Generated by Django 5.1.6 on 2025-02-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imgs', models.JSONField()),
                ('specs', models.JSONField()),
                ('inStock', models.IntegerField()),
                ('rating', models.FloatField()),
                ('reviews', models.JSONField()),
            ],
        ),
    ]
