# Generated by Django 5.1.6 on 2025-02-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyDatabse', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgs',
            field=models.ImageField(max_length=255, upload_to='dummyDatabse/images', verbose_name='Product Image'),
        ),
    ]
